version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
  
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    
  client-api-producer:
    build:
      context: ../client/api-producer/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CLOUDAMQP_URL=amqp://guest:guest@rabbitmq:5672/%2f
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - rabbitmq
    restart: unless-stopped