# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sample_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sample_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14sample_service.proto\x12\x0esample_service\"\xb5\x01\n\x14ProcessSampleRequest\x12\x12\n\nimage_uuid\x18\x01 \x01(\t\x12\x12\n\nimage_path\x18\x02 \x01(\t\x12\x44\n\x08metadata\x18\x03 \x03(\x0b\x32\x32.sample_service.ProcessSampleRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"_\n\x15ProcessSampleResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nprocess_id\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\")\n\x13SampleStatusRequest\x12\x12\n\nprocess_id\x18\x01 \x01(\t\"\x8a\x01\n\x14SampleStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nimage_uuid\x18\x03 \x01(\t\x12\x13\n\x0bresult_path\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\x03\x12\x14\n\x0c\x63ompleted_at\x18\x06 \x01(\x03\"\x0f\n\rHealthRequest\"1\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\x94\x02\n\rSampleService\x12\\\n\rProcessSample\x12$.sample_service.ProcessSampleRequest\x1a%.sample_service.ProcessSampleResponse\x12\\\n\x0fGetSampleStatus\x12#.sample_service.SampleStatusRequest\x1a$.sample_service.SampleStatusResponse\x12G\n\x06Health\x12\x1d.sample_service.HealthRequest\x1a\x1e.sample_service.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sample_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSSAMPLEREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_PROCESSSAMPLEREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_PROCESSSAMPLEREQUEST']._serialized_start=41
  _globals['_PROCESSSAMPLEREQUEST']._serialized_end=222
  _globals['_PROCESSSAMPLEREQUEST_METADATAENTRY']._serialized_start=175
  _globals['_PROCESSSAMPLEREQUEST_METADATAENTRY']._serialized_end=222
  _globals['_PROCESSSAMPLERESPONSE']._serialized_start=224
  _globals['_PROCESSSAMPLERESPONSE']._serialized_end=319
  _globals['_SAMPLESTATUSREQUEST']._serialized_start=321
  _globals['_SAMPLESTATUSREQUEST']._serialized_end=362
  _globals['_SAMPLESTATUSRESPONSE']._serialized_start=365
  _globals['_SAMPLESTATUSRESPONSE']._serialized_end=503
  _globals['_HEALTHREQUEST']._serialized_start=505
  _globals['_HEALTHREQUEST']._serialized_end=520
  _globals['_HEALTHRESPONSE']._serialized_start=522
  _globals['_HEALTHRESPONSE']._serialized_end=571
  _globals['_SAMPLESERVICE']._serialized_start=574
  _globals['_SAMPLESERVICE']._serialized_end=850
# @@protoc_insertion_point(module_scope)
