# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'image_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13image_service.proto\x12\rimage_service\"<\n\x10TestImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x14\n\x0cimage_format\x18\x02 \x01(\t\"4\n\x11TestImageResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x0f\n\rHealthRequest\"1\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xa5\x01\n\x0cImageService\x12N\n\tTestImage\x12\x1f.image_service.TestImageRequest\x1a .image_service.TestImageResponse\x12\x45\n\x06Health\x12\x1c.image_service.HealthRequest\x1a\x1d.image_service.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TESTIMAGEREQUEST']._serialized_start=38
  _globals['_TESTIMAGEREQUEST']._serialized_end=98
  _globals['_TESTIMAGERESPONSE']._serialized_start=100
  _globals['_TESTIMAGERESPONSE']._serialized_end=152
  _globals['_HEALTHREQUEST']._serialized_start=154
  _globals['_HEALTHREQUEST']._serialized_end=169
  _globals['_HEALTHRESPONSE']._serialized_start=171
  _globals['_HEALTHRESPONSE']._serialized_end=220
  _globals['_IMAGESERVICE']._serialized_start=223
  _globals['_IMAGESERVICE']._serialized_end=388
# @@protoc_insertion_point(module_scope)
