# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sample_service_pb2 as sample__service__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sample_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SampleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessSample = channel.unary_unary(
                '/sample_service.SampleService/ProcessSample',
                request_serializer=sample__service__pb2.ProcessSampleRequest.SerializeToString,
                response_deserializer=sample__service__pb2.ProcessSampleResponse.FromString,
                _registered_method=True)
        self.GetSampleStatus = channel.unary_unary(
                '/sample_service.SampleService/GetSampleStatus',
                request_serializer=sample__service__pb2.SampleStatusRequest.SerializeToString,
                response_deserializer=sample__service__pb2.SampleStatusResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/sample_service.SampleService/Health',
                request_serializer=sample__service__pb2.HealthRequest.SerializeToString,
                response_deserializer=sample__service__pb2.HealthResponse.FromString,
                _registered_method=True)


class SampleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessSample(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSampleStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SampleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessSample': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessSample,
                    request_deserializer=sample__service__pb2.ProcessSampleRequest.FromString,
                    response_serializer=sample__service__pb2.ProcessSampleResponse.SerializeToString,
            ),
            'GetSampleStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSampleStatus,
                    request_deserializer=sample__service__pb2.SampleStatusRequest.FromString,
                    response_serializer=sample__service__pb2.SampleStatusResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=sample__service__pb2.HealthRequest.FromString,
                    response_serializer=sample__service__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sample_service.SampleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sample_service.SampleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SampleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessSample(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sample_service.SampleService/ProcessSample',
            sample__service__pb2.ProcessSampleRequest.SerializeToString,
            sample__service__pb2.ProcessSampleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSampleStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sample_service.SampleService/GetSampleStatus',
            sample__service__pb2.SampleStatusRequest.SerializeToString,
            sample__service__pb2.SampleStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sample_service.SampleService/Health',
            sample__service__pb2.HealthRequest.SerializeToString,
            sample__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
